// import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/app.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HoangDV - CV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
